### PR TITLE
Added Credits 

### PR DESCRIPTION
**Pull request by IvoryXL**
You guys worked hard. Now you just need to make a icon for the Credits menu then it should work. Also edited video state

### CODE REVIEW

**Comment by YumDev21** [comment]
There shouldn't be Update VideoState.hx  commit. Just remove it

**Comment by MrClogsworthYT** [comment]
Yh I tried adding this but manufacturing didn't like the idea lemme check doe

**Comment by YumDev21** [comment]
ok

**Comment by MrClogsworthYT** [comment]
oh wait i just realized that this is different code than psych LOL imma fix conflicts

**Pull request merged**
