### PR TITLE
Fixed Some Shit

### PR DESCRIPTION
**Pull request by XuelDev**
Added Credits and Fixed some TitleState.hx shit

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Review by Juanen100 — APPROVED** [review]
Yeah, seems ok to me

**Comment by XuelDev** [comment]
:)

**Comment by Juanen100** [comment]
Had to reopen it so I could merge it

**Comment by Jotaro-Gaming** [comment]
> Had to reopen it so I could merge it

can u add me in discord again? Jotaro Gaming#4072

**Pull request merged**
