### PR TITLE
changelog for outdatedsubstate shit

### PR DESCRIPTION
**Pull request by MrClogsworthYT**
idk lol i just wanted to contribute
also ima put this in draft until im finished xdxd

### CODE REVIEW

**Comment by MrClogsworthYT** [comment]
@Manux123

**Comment by MrClogsworthYT** [comment]
alr everything should be good

**Comment by MrClogsworthYT** [comment]
since @JloorMC  is was active 3 hours ago im guessing he is online

**Comment by Juanen100** [comment]
What does this exactly?

**Comment by MrClogsworthYT** [comment]
@Manux123 yo

**Comment by Juanen100** [comment]
Yo

**Comment by Juanen100** [comment]
6 minutes ago and I got the e-mail now, my internet is crap

**Comment by MrClogsworthYT** [comment]
> 6 minutes ago and I got the e-mail now, my internet is crap

It just adds the features that have been added in each update but since it's basically impossible to make a bot that add a changelog  you have to modify changelog. Thing

**Comment by MrClogsworthYT** [comment]
I'm not really sure it works so I have allowed edits by maintainers

**Comment by Juanen100** [comment]
Kade Engine is the best example. Kade Dev just updates the changelog with every update. There isn't a bot to make it, you just, update it

**Comment by Juanen100** [comment]
Also I saw some stuff that is incorrect in your code, but I'll change it when the update

**Pull request merged**
