### PR TITLE
INTRO TEXT BABY

### PR DESCRIPTION
**Pull request by XuelDev**
I fixed the intro text thingy

### CODE REVIEW

**Comment by Juanen100** [comment]
Epic



Why is the description of the commit Fuck You lmao

**Comment by XuelDev** [comment]
I really don't know

**Comment by XuelDev** [comment]
@Juanen100 What is your discord i'll add you on there if you want

**Comment by Juanen100** [comment]
My discord is Juanen 100#4903

**Comment by XuelDev** [comment]
I added you

**Comment by Juanen100** [comment]
Forgot to merge lmao

**Comment by XuelDev** [comment]
lol

**Pull request merged**
