### PR TITLE
credits thingy

### PR DESCRIPTION
**Pull request by MrClogsworthYT**
DONT MERGE YET!!!!!

### CODE REVIEW

**Comment by MrClogsworthYT** [comment]
please put the black thingy by editing my commits

**Comment by MrClogsworthYT** [comment]
I'll do more stuff later for now pls don't close :D

**Comment by Juanen100** [comment]
MainMenu was glitched so i fixed it

**Comment by MrClogsworthYT** [comment]
> MainMenu was glitched so i fixed it

oh thx but there are still errors lol

**Comment by Juanen100** [comment]
There u go lmao

**Comment by MrClogsworthYT** [comment]
> There u go lmao

noice!

**Comment by MrClogsworthYT** [comment]
alright since it can be compiled now it should be good to merge

**Comment by MrClogsworthYT** [comment]
btw add the credits

**Comment by Juanen100** [comment]
yeet

**Pull request merged**
