### PR TITLE
actions for prs to make sure they are able to compile

### PR DESCRIPTION
**Pull request by MrClogsworthYT**

### CODE REVIEW

**Comment by MrClogsworthYT** [comment]
DONT MERGE YET

**Comment by MrClogsworthYT** [comment]
I need to do the final thing to fix it

**Comment by Juanen100** [comment]
K, good thing I didn't merge before

**Comment by Juanen100** [comment]
K

**Comment by Juanen100** [comment]
Why does it keep failing?

**Comment by MrClogsworthYT** [comment]
> Why does it keep failing?

idk

**Comment by MrClogsworthYT** [comment]
> Why does it keep failing?

turns out I forgot to add newgrounds haxelib  lol

**Comment by Juanen100** [comment]
lol

**Comment by MrClogsworthYT** [comment]
I ALWAYS FORGOT THE MOST IMPORTANT THINGS AAAAAA

**Comment by Juanen100** [comment]
BRUH

**Comment by Juanen100** [comment]
Hey. Do u have discord?

**Comment by MrClogsworthYT** [comment]
> BRUH

bruh indeed

**Comment by Juanen100** [comment]
is cuz is easier for me to communicate with u through discord instead of github

**Comment by MrClogsworthYT** [comment]
> Hey. Do u have discord?

MrClogDevඞ#8531

**Comment by Juanen100** [comment]
> > Hey. Do u have discord?
> 
> MrClogDevඞ#8531

nice

**Comment by MrClogsworthYT** [comment]
> > > Hey. Do u have discord?
> > 
> > 
> > MrClogDevඞ#8531
> 
> nice

send me a friend request

**Comment by MrClogsworthYT** [comment]
it works 😎

**Comment by Juanen100** [comment]
epic

**Pull request merged**
